### ISSUE TITLE
Updated analysis: molecular-subtyping modules update for OT 

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#98]
#### What analysis module should be updated and why?
 
We need to preprocess data released files for subtyping, please refer to the table here for additional info https://www.notion.so/d3b/0a455919593147b2a1234655037f5cb9?v=a4783dee385c4dd2b1453b9caca09749

The following are pre-processing modules needed for molecular-subtping-* modules
- [x] RNA #94 
- [x] RNA #95 
- [x] RNA #96 
- [x] DNA #114 
- [x] DNA #115
- [x] RNA +DNA #97 

After the above is complete we will need to update the filename update in the following modules:
( If issues arrise other than filename update we will create a new issue and tag them under each module here)
- [x] molecular-subtyping-MB
- [x] molecular-subtyping-CRANIO
- [x] molecular-subtyping-EPN
- [x] molecular-subtyping-embryonal
- [x] molecular-subtyping-chordoma
- [x] molecular-subtyping-EWS
- [x] molecular-subtyping-neurocytoma
- [x] molecular-subtyping-HGG
- [x] molecular-subtyping-LGAT
- [x] molecular-subtyping-pathology
- [x] molecular-subtyping-integrate

#### What changes need to be made? Please provide enough detail for another participant to make the update.
 - Replace occurrence of `pbta-snv-consensus-mutation.maf.tsv.gz` to `snv-consensus-plus-hotspots.maf.tsv.gz` .
 - Currently the scripts are run separately for `pbta-gene-expression-rsem-fpkm-collapsed.stranded.rds` and `pbta-gene-expression-rsem-fpkm-collapsed.polya.rds` please use the `gene-expression-rsem-tpm-collapsed.rds` file and be sure to subset the rds files to use Kids_First_Biospecimen_ID that belong to `PBTA` and `GMKF` cohorts within the code.
- Change each occurrence of pbta-fusion-putative-oncogenic.tsv to fusion-putative-oncogenic.tsv

- Change each occurrence of pbta-histologies.tsv to histologies.tsv

#### What input data should be used? Which data were used in the version being updated?
snv-consensus-plus-hotspots.maf.tsv.gz
gene-expression-rsem-tpm-collapsed.rds
fusion-putative-oncogenic.tsv
histologies.tsv
pbta-histologies-base-adapt-04142022.tsv (ADAPT file)

**TODO** the CNV files need to be merged and renamed 
consensus_seg_annotated_cn_autosomes.tsv.gz
consensus_seg_annotated_cn_x_and_y.tsv.gz
cnvkit_annotated_cn_x_and_y.tsv.gz
cnvkit_annotated_cn_autosomes.tsv.gz

#### When do you expect the revised analysis will be completed?
1 -1.5 week

**Comment by runjin326** [comment]
We can close this for now since we will be using one molecular subtype module going forward.

**Comment by runjin326** [comment]
We still need to adapt the remaining modules for OT to generate subtypes for comparisons.

**Comment by jharenza** [comment]
@komalsrathi can you work on this ticket?

**Comment by komalsrathi** [comment]
yes I can start working on this after [this](https://github.com/PediatricOpenTargets/ticket-tracker/issues/279) ticket is closed.

**Comment by komalsrathi** [comment]
@jharenza thanks for clarifying that this can be done quickly - so I can work on it first (should not take longer than a day at most according to our discussion) and resume BC after this.

**Comment by komalsrathi** [comment]
@jharenza would 1 PR be okay for all these changes or do you want 1 PR per module?

**Comment by jharenza** [comment]
I think one will be fine

**Comment by komalsrathi** [comment]
Still working on this:

@jharenza some updates before I can create a PR:

I was able to edit and run the CRANIO, chordoma, EWS,  neurocytoma pretty easily and successfully.  

For the `molecular-subtyping-embryonal` module, it keeps failing on Docker with vector memory exhaust error. I saw where the issue happens and it is because of [this function](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/molecular-subtyping-embryonal/02-generate-subset-files.R#L54-L75). So in this module, we are first z-scoring the FULL RNA-seq expression dataset and then subsetting to the relevant ids (in this case embryonal samples) - but why do we need the full dataset for z-scoring when the goal of this module is molecular subtyping of embryonal samples? Shouldn't we first subset to ONLY embryonal samples and then do the z-scoring? Especially now that we have so many different histologies and cohorts (including GTEx normal samples) - I don't think it makes sense to z-score the full data. Do you have any suggestions?

Finally, for `molecular-subtyping-EPN`, I was getting some errors in the Python scripts (after changing the relevant filenames) that I was unable to figure out exactly. So I am converting the python scripts to R. Will keep you updated.

**Comment by komalsrathi** [comment]
@jharenza To test the 04-table-prep.Rmd script under molecular-subtyping-embryonal module, I would need [these](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/molecular-subtyping-embryonal/04-table-prep.Rmd#L110-L113) files. I don't think we push `cnvkit_annotated_cn_x_and_y.tsv.gz` and `controlfreec_annotated_cn_x_and_y.tsv.gz` to the repo because I recall they are quite large - do you know if there is an s3 bucket I can fetch these from or do I need to rerun the `focal-cn-file-preparation` module? If I need to re-run, it looks like it needs the `v38` gencode file which I cannot find under `data/` as well. Any idea about these input files?

**Comment by jharenza** [comment]
>For the molecular-subtyping-embryonal module, it keeps failing on Docker with vector memory exhaust error. I saw where the issue happens and it is because of [this function](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/molecular-subtyping-embryonal/02-generate-subset-files.R#L54-L75). So in this module, we are first z-scoring the FULL RNA-seq expression dataset and then subsetting to the relevant ids (in this case embryonal samples) - but why do we need the full dataset for z-scoring when the goal of this module is molecular subtyping of embryonal samples? Shouldn't we first subset to ONLY embryonal samples and then do the z-scoring? Especially now that we have so many different histologies and cohorts (including GTEx normal samples) - I don't think it makes sense to z-score the full data. Do you have any suggestions?

yes, 100% we should subset and z-score



Hmm - 
>@jharenza To test the 04-table-prep.Rmd script under molecular-subtyping-embryonal module, I would need [these](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/molecular-subtyping-embryonal/04-table-prep.Rmd#L110-L113) files. I don't think we push cnvkit_annotated_cn_x_and_y.tsv.gz and controlfreec_annotated_cn_x_and_y.tsv.gz to the repo because I recall they are quite large - do you know if there is an s3 bucket I can fetch these from or do I need to rerun the focal-cn-file-preparation module? If I need to re-run, it looks like it needs the v38 gencode file which I cannot find under data/ as well. Any idea about these input files?

It looks like these aren't even being used here - there is some BCOR check because it is on chr X, but I would say we can use the consensus seg here rather than all 3.
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/6e0495d518b605ce3bfa9b286490253c80ee9b87/analyses/molecular-subtyping-embryonal/04-table-prep.Rmd#L278-L297

**Comment by komalsrathi** [comment]
Great, thank you! I'll make those changes.

**Comment by komalsrathi** [comment]
Just keeping you updated that making some final changes to the EPN module - will create a PR after testing everything so latest by EOB.

**Comment by runjin326** [comment]
Completed with PR171 merged.
